Evg/models
ratingus/ratingus-backend pull request #8
Opened 2024-04-02 15:40 UTC by PiPuKaPRo

изменил инит и модели

2024-04-02 15:58 UTC, burunyuu23 requested changes
1. Односторонняя привязка без связи @OneToOne
2. Наследование User, Student, Teacher и т.д. что я тебе говорил на созвоне

2024-04-02 15:58 UTC, burunyuu23 commented on src/main/java/ru/dnlkk/ratingusbackend/model/Class.java
> +    private UserCode userCode;
убери это. только у кода может быть класс, у класс код не должен быть

2024-04-02 15:58 UTC, burunyuu23 commented on src/main/java/ru/dnlkk/ratingusbackend/model/Announcement.java
> +
не user, а creator (создать объявления)

2024-04-02 15:58 UTC, burunyuu23 commented on src/main/java/ru/dnlkk/ratingusbackend/model/School.java
> +    private String address;
в @Column address с двумя s

2024-04-02 15:58 UTC, burunyuu23 commented on src/main/java/ru/dnlkk/ratingusbackend/model/UserCode.java
> +    private Class c_lass;
поменять

2024-04-02 15:58 UTC, burunyuu23 commented on src/main/java/ru/dnlkk/ratingusbackend/model/UserRole.java
> +    private User user;
помимо user которому предназначен код, ещё нужен User creator (менеджер платформы, который создал код (можно поиграться с наследованием и сделать классы Teacher, Student, Manager))

2024-04-02 15:58 UTC, burunyuu23 commented on src/main/resources/db_init/init.sql
> +
creatorId добавь менеджера, который создал код

2024-04-02 16:30 UTC, PiPuKaPRo commented on src/main/java/ru/dnlkk/ratingusbackend/model/Announcement.java
> +
изменил

2024-04-02 16:31 UTC, PiPuKaPRo commented on src/main/java/ru/dnlkk/ratingusbackend/model/School.java
> +    private String address;
изменил

2024-04-02 16:31 UTC, PiPuKaPRo commented on src/main/java/ru/dnlkk/ratingusbackend/model/UserCode.java
> +    private Class c_lass;
поменял

2024-04-02 17:00 UTC, PiPuKaPRo commented on src/main/resources/db_init/init.sql
> +
сделал

2024-04-02 17:20 UTC, PiPuKaPRo commented on src/main/java/ru/dnlkk/ratingusbackend/model/UserRole.java
> +    private User user;
Добавил

2024-04-04 18:53 UTC, burunyuu23 requested changes

2024-04-04 18:53 UTC, burunyuu23 commented on src/main/java/ru/dnlkk/ratingusbackend/model/Class.java
> +    private UserCode userCode;
короче сделай просто OneToMany

2024-04-04 18:53 UTC, burunyuu23 commented on src/main/java/ru/dnlkk/ratingusbackend/model/School.java
> +    private List<UserCode> userCodes;
перенести в Class (коды в школе получать по классам)

2024-04-04 18:53 UTC, burunyuu23 commented on src/main/java/ru/dnlkk/ratingusbackend/model/StudentLesson.java
> +    private int Id;
id с маленькой буквы, мы не в C#

2024-04-04 18:53 UTC, burunyuu23 commented on src/main/java/ru/dnlkk/ratingusbackend/model/Timetable.java
> +    private School school;
че?
то есть ты хочешь сказать что у нас будет объект Timetable с lessonNumber = 1 с началом в 8:00 и концом в 8:45 и это OneToOne со школой? вообще не так, переделайте

2024-04-04 18:53 UTC, burunyuu23 commented on src/main/java/ru/dnlkk/ratingusbackend/model/UserCode.java
> +    private Class userClass;
ManyToOne

2024-04-05 12:32 UTC, PiPuKaPRo commented on src/main/java/ru/dnlkk/ratingusbackend/model/StudentLesson.java
> +    private int Id;
сделал

2024-04-05 12:33 UTC, PiPuKaPRo commented on src/main/java/ru/dnlkk/ratingusbackend/model/UserCode.java
> +    private Class userClass;
сделал

2024-04-05 12:33 UTC, PiPuKaPRo commented on src/main/java/ru/dnlkk/ratingusbackend/model/School.java
> +    private List<UserCode> userCodes;
сделал

2024-04-05 20:29 UTC, burunyuu23 submitted a review, later dismissed

2024-04-05 20:31 UTC, merged